# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cyborg.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import numpy as np
import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QApplication,QWidget,QPushButton,QHBoxLayout,QFileDialog



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(983, 731)
        self.browse = QtWidgets.QPushButton(Dialog)
        self.browse.setGeometry(QtCore.QRect(210, 550, 191, 71))
        self.browse.setObjectName("browse")
        self.convert = QtWidgets.QPushButton(Dialog)
        self.convert.setGeometry(QtCore.QRect(510, 550, 191, 71))
        self.convert.setObjectName("convert")
        self.image_1 = QtWidgets.QLabel(Dialog)
        self.image_1.setGeometry(QtCore.QRect(100, 100, 321, 321))
        self.image_1.setScaledContents(True)
        self.image_1.setObjectName("image_1")
        self.image_2 = QtWidgets.QLabel(Dialog)
        self.image_2.setGeometry(QtCore.QRect(600, 100, 321, 321))
        self.image_2.setScaledContents(True)
        self.image_2.setObjectName("image_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.browse.clicked.connect(self.openFileDialog)
        self.convert.clicked.connect(self.convertFile)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.browse.setText(_translate("Dialog", "Browse"))
        self.convert.setText(_translate("Dialog", "Convert"))
        self.image_1.setText(_translate("Dialog", "TextLabel"))
        self.image_2.setText(_translate("Dialog", "TextLabel"))


    def openFileDialog(self):
        option=QFileDialog.Options()
        widget=QWidget()
        file=QFileDialog.getOpenFileName(widget,"Open Single File","Default File", 'Images (*.png, *.xmp *.jpg)',options=option)
        self.image_1.setPixmap(QtGui.QPixmap(file[0]))
        img=cv2.imread(file[0],0)
        cv2.imwrite('output.jpg',img)

    def convertFile(self):
        
        self.image_2.setPixmap(QtGui.QPixmap("output.jpg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
